version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.24.1
      - image: circleci/node:12.19.0
    steps:
      - checkout
      - run:
          name: install-dependent
          command: npm install
      - run:
          name: build
          command: npm run build
